integration-android:
  image: cirrusci/flutter:3.24.4
  variables:
    apiLevel: "34"
    target: "google_apis"
    arch: "x86"
    deviceName: "android_emulator"
    deviceType: "pixel"
    FLAVOR: "prod"
  artifacts:
    when: always
    paths:
      - e2e_output.log
  script:
    # set up the emulator
    - sdkmanager "platform-tools" "platforms;android-${apiLevel}"
    - sdkmanager --install "system-images;android-${apiLevel};${target}${arch}"
    - sdkmanager --update
    - echo "y" | sdkmanager --licenses
    - sdkmanager --list
    - echo "no" | avdmanager -v create avd --force --name "${deviceName}" --package "system-images;android-${apiLevel};${target};${arch}" --tag "${target}" --sdcard 128M --device "${deviceType}"
    - emulator -avd "${deviceName}" -no-audio -no-window -no-snapstorage -no-snapshot -gpu swiftshader_indirect -no-boot-anim -no-accel -wipe-data -skip-adb-auth &
    - adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
    - flutter doctor -v
    # run the integration tests
    # with a trick that prevent the job from failing due to failure to uninstall app
    # if you don't need this trick, you can simply run:
    # flutter drive --driver=test_driver/integration_test.dart --target=integration_test/main.dart --flavor ${FLAVOR}
    - set +e
    - (flutter drive --driver=test_driver/integration_test.dart --target=integration_test/main.dart --flavor ${FLAVOR}|| true) > e2e_output.log 2>&1 | (grep -q "Failed to uninstall app" && (echo "Failed to uninstall app." && exit 0))
    - set -e
    - cat e2e_output.log | grep -q "Some tests failed." && (echo "Some tests failed. Exiting with error code." >&2 && exit 1)

integration-ios:
  tags:
    - shared-macos-amd64
  image: macos-12-xcode-13
  variables:
    FLAVOR: "e2e"
  script:
    # set up the simulator
    - xcrun simctl list runtimes
    - xcrun simctl create "e2e test" "iPhone 12" "com.apple.CoreSimulator.SimRuntime.iOS-15-5"
    - xcrun xctrace list devices
    - |
        UDID=$(xcrun xctrace list devices | grep "^iPhone 12 Simulator(15.5)" | awk '{gsub(/[()]/,""); print $NF}')      
        echo $UDID
        xcrun simctl boot "${UDID:?No Simulator with this name found}"
    - flutter doctor -v
    # run the integration tests
    - flutter drive --driver=test_driver/integration_test.dart --target=integration_test/main.dart --flavor ${FLAVOR}
